import sqlite3

connection = sqlite3.connect("../lessons/FruitBasket.db")
cur = connection.cursor()
cur.execute("DROP TABLE Fruits;")
connection.commit()
cur.execute("CREATE TABLE Fruits (Name TEXT, Color TEXT);")
connection.commit()
cur.execute("INSERT INTO Fruits (Name, Color) VALUES ('Apple', 'Red');")
cur.execute("INSERT INTO Fruits (Name, Color) VALUES ('Banana', 'Yellow');")
cur.execute("INSERT INTO Fruits (Name, Color) VALUES ('Orange', 'Orange');")
connection.commit()
cur.execute("UPDATE Fruits SET Color = 'Green' WHERE Name = 'Apple';")
connection.commit()
cur.execute("SELECT name,color FROM Fruits WHERE Color = 'Yellow';")
yellow_fruits = cur.fetchall()
print("Yellow fruits:", yellow_fruits)
cur.execute("SELECT name,color FROM Fruits;")
all_fruits = cur.fetchall()
print("All fruits:", all_fruits)
connection.close()
